name: fast_cached_network_image
description: A flutter package to cache network image fastly without any native dependencies.You can add beautiful loaders, percentage indicators and error builder.
version: 1.3.2+4
homepage: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image

topics:
  - cache
  - image
  - photo
  - download
  - network


environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  hive_ce: ^2.10.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
