name: fast_cached_network_image
description: A flutter package to cache network image fastly without any native dependencies.You can add beautiful loaders, percentage indicators and error builder.
version: 1.5.0
homepage: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image
repository: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image
issue_tracker: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image/issues

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.1
  hive_flutter: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
